export  { default as AboutView } from './AboutView.vue';
export  { default as DashboardView } from './DashboardView.vue';
// export  { default as ForgotPasswordView } from './ForgotPasswordView';
export  { default as LoginView } from './LoginView.vue';
export  { default as UserProfileView } from './UserProfileView.vue';
export  { default as UserVerificationView } from './UserVerificationView.vue';
export  { default as RegisterView } from './RegisterView.vue';
export  { default as AccessMapView } from './AccessMapView.vue';
export  { default as VerificationConfirmedView } from './VerificationConfirmedView.vue';
export { default as LandingView} from './LandingView.vue';
export { default as MapQueueView} from './MapQueueView.vue';
export { default as PathHistoryView} from './PathHistoryView.vue';
export { default as PairDeviceView } from './PairDeviceView.vue';
export { default as AdminView} from './AdminView.vue';
export { default as DashboardAdminView} from './DashboardAdminView.vue';